import DynamicalCStarAlgebras
import Lean
open Lean Elab Command
run_cmd do
  let env ← getEnv
  -- Checked manuscript statements; synchronized with paper_roots in coverage.json.
  let roots : Array Name := #[
    `DynamicalCStarAlgebras.CoarseStructure.restrictReal_largest,
    `DynamicalCStarAlgebras.realPullbackPseudoMetric_dist,
    `DynamicalCStarAlgebras.isCoarseReal_iff,
    `DynamicalCStarAlgebras.matrixEntry_eq_inner,
    `DynamicalCStarAlgebras.uniformRoe_metric_eq,
    `DynamicalCStarAlgebras.uniformRoe_restrictReal_subset,
    `DynamicalCStarAlgebras.coordinateProjection_eq_self_iff,
    `DynamicalCStarAlgebras.isClosed_quasiLocal,
    `DynamicalCStarAlgebras.uniformRoe_subset_quasiLocal,
    `DynamicalCStarAlgebras.isQuasiLocal_iff_metric,
    `DynamicalCStarAlgebras.isQuasiLocal_iff_modulus_tendsto,
    `DynamicalCStarAlgebras.finitePropagation_iff_modulus_eventually_zero,
    `DynamicalCStarAlgebras.diagonalFlow_norm,
    `DynamicalCStarAlgebras.diagonalFlow_mem_uniformRoe,
    `DynamicalCStarAlgebras.diagonalFlowEquiv,
    `DynamicalCStarAlgebras.continuityPointsStarSubalgebra_isClosed,
    `DynamicalCStarAlgebras.mem_continuityPoints_iff_continuousAt_zero,
    `DynamicalCStarAlgebras.continuous_inner_diagonalFlow,
    `DynamicalCStarAlgebras.matrixEntry_averagingOperator,
    `DynamicalCStarAlgebras.inner_averagingOperator,
    `DynamicalCStarAlgebras.averagingOperatorL1_norm_le,
    `DynamicalCStarAlgebras.averagingOperatorL1_toL1,
    `DynamicalCStarAlgebras.averagingOperator_sub_norm_le,
    `DynamicalCStarAlgebras.averagingOperator_mem_invariant_subalgebra,
    `DynamicalCStarAlgebras.fejerKernel_zero,
    `DynamicalCStarAlgebras.integrable_fejerKernel,
    `DynamicalCStarAlgebras.fejerKernel_tail_bound,
    `DynamicalCStarAlgebras.matrixEntry_fejerAverage_eq_zero,
    `DynamicalCStarAlgebras.tendsto_fejerAverage,
    `DynamicalCStarAlgebras.integral_fejerKernel,
    `DynamicalCStarAlgebras.integral_norm_fejerKernel,
    `DynamicalCStarAlgebras.fourierPlus_fejerKernel,
    `DynamicalCStarAlgebras.continuityPoint_mem_closure_finitePropagation,
    `DynamicalCStarAlgebras.theoremA,
    `DynamicalCStarAlgebras.fourierPlus_valleePoussin_plateau,
    `DynamicalCStarAlgebras.integral_norm_valleePoussin_le,
    `DynamicalCStarAlgebras.uniformRoe_inter_continuityPoints,
    `DynamicalCStarAlgebras.coe_coarseContinuityPointsStarSubalgebra,
    `DynamicalCStarAlgebras.coarseContinuityPointsStarSubalgebra_isClosed,
    `DynamicalCStarAlgebras.uniformRoe_subset_coarseContinuityPoints,
    `DynamicalCStarAlgebras.diagonalFlow_mem_quasiLocal,
    `DynamicalCStarAlgebras.diagonalMultiplierStarHom,
    `DynamicalCStarAlgebras.diagonalMultiplier_isometry,
    `DynamicalCStarAlgebras.diagonalMultiplier_mem_uniformRoe,
    `DynamicalCStarAlgebras.matrixEntry_iterate_diagonalCommutator,
    `DynamicalCStarAlgebras.iterate_diagonalCommutator_bounds,
    `DynamicalCStarAlgebras.duhamel_norm_le,
    `DynamicalCStarAlgebras.lipschitzWith_diagonalFlow_of_commutator,
    `DynamicalCStarAlgebras.quasiLocalStarSubalgebra_isClosed,
    `DynamicalCStarAlgebras.quasiLocalModulus_algebra,
    `DynamicalCStarAlgebras.exponentialQuasiLocal_algebra,
    `DynamicalCStarAlgebras.polynomialQuasiLocal_algebra,
    `DynamicalCStarAlgebras.decayAlgebra_inclusions,
    `DynamicalCStarAlgebras.norm_pow_delta_le_compression,
    `DynamicalCStarAlgebras.uniformRoe_algebra,
    `DynamicalCStarAlgebras.IsStripExtension.matrixEntry_eq,
    `DynamicalCStarAlgebras.IsStripExtension.unique,
    `DynamicalCStarAlgebras.isEntireExponentialType_iff_finitePropagation,
    `DynamicalCStarAlgebras.exponentialAnalyticPoints_algebra,
    `DynamicalCStarAlgebras.uniformRoe_subset_exponentialAnalyticPoints,
    `DynamicalCStarAlgebras.lipschitz_detect,
    `DynamicalCStarAlgebras.infinitePropagation_lipschitz_detect,
    `DynamicalCStarAlgebras.finitePropagation_iff_coarse_entireExponential,
    `DynamicalCStarAlgebras.uniformRoe_eq_exponentialAnalyticPoints,
    `DynamicalCStarAlgebras.entire_coefficient_all_rates,
    `DynamicalCStarAlgebras.quasiLocal_commutator_bound,
    `DynamicalCStarAlgebras.quasiLocal_subset_coarseContinuityPoints,
    `DynamicalCStarAlgebras.nonQuasiLocal_finite_buffer_witnesses,
    `DynamicalCStarAlgebras.nonQuasiLocal_coarse_discontinuous,
    `DynamicalCStarAlgebras.quasiLocal_eq_coarseContinuityPoints,
    `DynamicalCStarAlgebras.theoremB,
    `DynamicalCStarAlgebras.IsStripExtension.strip_norm_supremum,
    `DynamicalCStarAlgebras.gapEstimate,
    `DynamicalCStarAlgebras.weightedBound_closed_cover,
    `DynamicalCStarAlgebras.exists_uniform_weighted_gluing,
    `DynamicalCStarAlgebras.strip_analytic_hasExponentialDecay,
    `DynamicalCStarAlgebras.stripAnalyticPoints_subset_exponentialQuasiLocal,
    `DynamicalCStarAlgebras.stripAnalyticPoints_algebra,
    `DynamicalCStarAlgebras.stripExtension_of_factorial_moments,
    `DynamicalCStarAlgebras.graph_slicing_estimate,
    `DynamicalCStarAlgebras.theoremE,
    `DynamicalCStarAlgebras.exponentialQuasiLocal_subset_stripAnalyticPoints,
    `DynamicalCStarAlgebras.CoarseGraphUnion.exists_compact_offBlock,
    `DynamicalCStarAlgebras.vertex_expansion_uniform_separation,
    `DynamicalCStarAlgebras.trace_projection_estimate,
    `DynamicalCStarAlgebras.small_projection_compression_bound,
    `DynamicalCStarAlgebras.CoarseGraphUnion.projection_not_mem_polynomialQuasiLocal,
    `DynamicalCStarAlgebras.CoarseGraphUnion.projection_mem_polynomialQuasiLocal,
    `DynamicalCStarAlgebras.volume_approximation,
    `DynamicalCStarAlgebras.atMostExponentialGrowth_iff_volume_bound,
    `DynamicalCStarAlgebras.quasiLocal_inter_continuityPoints,
    `DynamicalCStarAlgebras.CoarseDisjointUnion.bijectivelyCoarselyEquivalent,
    `DynamicalCStarAlgebras.coarse_uniformlyLocallyFinite_iff,
    `DynamicalCStarAlgebras.continuousOrbitSubalgebra_isClosed,
    `DynamicalCStarAlgebras.exists_unique_weakIntegral,
    `DynamicalCStarAlgebras.isStripExponentialType_iff_stripAnalytic,
    `DynamicalCStarAlgebras.iteratedCommutator_characterization,
    `DynamicalCStarAlgebras.fejerAverage_sub_norm_le_of_local_bound,
    `DynamicalCStarAlgebras.IsLargeScaleGeodesic.atMostExponentialGrowth,
    `DynamicalCStarAlgebras.graphMetric_atMostExponentialGrowth,
    `DynamicalCStarAlgebras.quasiLocal_smoothing,
    `DynamicalCStarAlgebras.height_band_nonzero_compression,
    `DynamicalCStarAlgebras.controlled_operator_partial_translation_decomposition,
    `DynamicalCStarAlgebras.metricPropagation_lt_top_iff,
    `DynamicalCStarAlgebras.maximalULF_counterexample,
    `DynamicalCStarAlgebras.isCoarseReal_iff_uniformRoe_continuous,
    `DynamicalCStarAlgebras.exists_frame_subspace,
    `DynamicalCStarAlgebras.expanderGraphUnion_of_raw_data,
    `DynamicalCStarAlgebras.exists_quarter_power_subspace,
    `DynamicalCStarAlgebras.exists_logarithmic_rank_subspace,
    `DynamicalCStarAlgebras.CoarseGraphUnion.exists_assumption_one_projection,
    `DynamicalCStarAlgebras.ExpanderGraphUnion.strict_decay_inclusions,
    `DynamicalCStarAlgebras.ExpanderGraphUnionData.exists_matrixProduct_embedding,
    `DynamicalCStarAlgebras.ExpanderGraphUnionData.exists_matrixProduct_embedding_strip,
    `DynamicalCStarAlgebras.theoremC,
    `DynamicalCStarAlgebras.theoremD,
    `DynamicalCStarAlgebras.boundedMatrixProduct_not_range_subset_uniformRoe,
    `DynamicalCStarAlgebras.AreBijectivelyCoarselyEquivalent.dynamical_algebras,
    `DynamicalCStarAlgebras.AreBijectivelyCoarselyEquivalent.graph_exponential_algebras,
    `DynamicalCStarAlgebras.analyticOrbitSubalgebra_dense,
    `DynamicalCStarAlgebras.regularityPoints_algebra,
    `DynamicalCStarAlgebras.regularityPoints_between_Roe_quasiLocal,
    `DynamicalCStarAlgebras.AreBijectivelyCoarselyEquivalent.regularity_algebras,
    `DynamicalCStarAlgebras.uniformRoe_eq_quasiLocal_of_propertyA,
    `DynamicalCStarAlgebras.hasPropertyA_iff_probabilityRows,
    `DynamicalCStarAlgebras.intermediate_eq_uniformRoe_of_propertyA,
    `DynamicalCStarAlgebras.polynomialDecay_not_coarse_invariant,
    `DynamicalCStarAlgebras.exponentialDecay_not_coarse_invariant,
    `DynamicalCStarAlgebras.graph_diameter_le_log_card,
    `DynamicalCStarAlgebras.CoarseStructure.ofMetric_isMetrizable,
    `DynamicalCStarAlgebras.finitelyGeneratedGroup_cayley_geometry,
    `DynamicalCStarAlgebras.exists_discontinuous_diagonal_preflow,
    `DynamicalCStarAlgebras.maximalULF_not_metrizable,
    `DynamicalCStarAlgebras.uniformRoe_not_subset_closure_countable,
    `DynamicalCStarAlgebras.exists_boundedDegree_coarseEmbedding,
    `DynamicalCStarAlgebras.entireAnalyticPoints_eq_exponentialAnalyticPoints]
  let mut todo := roots
  let mut seen : NameSet := {}
  let mut rows : Array Json := #[]
  while !todo.isEmpty do
    let name := todo.back!
    todo := todo.pop
    if seen.contains name then continue
    seen := seen.insert name
    let some idx := env.getModuleIdxFor? name | continue
    let mod := env.header.moduleNames[idx.toNat]!
    if !"DynamicalCStarAlgebras".isPrefixOf mod.toString then continue
    let some ci := env.find? name | continue
    let deps := ci.type.getUsedConstants ++ (ci.value? true |>.map Expr.getUsedConstants |>.getD #[])
    todo := todo ++ deps
    rows := rows.push <| Json.mkObj [("name", toJson name.toString), ("module", toJson mod.toString),
      ("deps", toJson (deps.map Name.toString))]
  IO.println <| (Json.mkObj [("roots", toJson (roots.map Name.toString)),
    ("declarations", Json.arr rows)]).compress
